version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 10
    rebase-strategy: auto
    schedule:
      day: monday
      interval: weekly
      timezone: Europe/Berlin
    labels:
      - dependencies
    assignees:
      - psachmann

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      timezone: Europe/Berlin
    labels:
      - dependencies
    assignees:
      - psachmann
