version: "3"

services:
  postgres:
    image: docker.io/postgres:15.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=todos
