version: "3"

services:
  mariadb:
    image: docker.io/mariadb:11.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=todos
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=password
