name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Build
        run: dotnet nuke build

      - name: Test
        run: dotnet nuke test
